name: Your New Jekyll Site
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /journal/:year/:month/:day/:title/
media: 'assets/img'
